import { useEffect, useState } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import {
  FileOutput,
  FileSpreadsheet,
  Download,
  ShieldCheck,
  CheckCircle2,
  RefreshCw,
  Clock
} from 'lucide-react'
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Alert } from '@/components/ui/alert'
import { LoadingScreen } from '@/components/ui/spinner'
import { reportService, datasetService } from '@/services/api'
import { formatDate } from '@/utils/formatters'

export default function Reports() {
  const { id } = useParams()
  const navigate = useNavigate()

  const [dataset, setDataset] = useState(null)
  const [isLoading, setIsLoading] = useState(true)
  const [downloadingPdf, setDownloadingPdf] = useState(false)
  const [downloadingExcel, setDownloadingExcel] = useState(false)
  const [error, setError] = useState(null)

  useEffect(() => {
    loadData()
  }, [id])

  const loadData = async () => {
    try {
      setIsLoading(true)
      setError(null)
      const datasetRes = await datasetService.getById(id)
      setDataset(datasetRes.data.data)
    } catch (err) {
      setError(err.response?.data?.message || 'Failed to load report options.')
    } finally {
      setIsLoading(false)
    }
  }

  const handleDownloadPdf = async () => {
    try {
      setDownloadingPdf(true)
      setError(null)

      const res = await reportService.downloadPdf(id)
      const blob = new Blob([res.data], { type: 'application/pdf' })
      const url = window.URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `${dataset?.originalName || 'dataforge'}_Quality_Report.pdf`
      document.body.appendChild(a)
      a.click()
      a.remove()
      window.URL.revokeObjectURL(url)
    } catch (err) {
      setError('Could not download PDF report. Ensure Python ReportLab is ready.')
    } finally {
      setDownloadingPdf(false)
    }
  }

  const handleDownloadExcel = async () => {
    try {
      setDownloadingExcel(true)
      setError(null)

      const res = await reportService.downloadExcel(id)
      const blob = new Blob([res.data], {
        type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
      })
      const url = window.URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `${dataset?.originalName || 'dataforge'}_Cleaned.xlsx`
      document.body.appendChild(a)
      a.click()
      a.remove()
      window.URL.revokeObjectURL(url)
    } catch (err) {
      setError('Could not download Cleaned Excel file. Run data cleaning first.')
    } finally {
      setDownloadingExcel(false)
    }
  }

  if (isLoading) return <LoadingScreen message="Loading report downloads..." />

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <div className="flex items-center gap-2 mb-1">
          <Badge variant="primary">Phase 11</Badge>
          <span className="text-xs text-gray-500 font-mono">ID: {id}</span>
        </div>
        <h1 className="text-2xl font-bold text-gray-900 dark:text-gray-100">
          Exports & Downloads
        </h1>
        <p className="mt-1 text-sm text-gray-500 dark:text-gray-400">
          Download publication-ready PDF validation reports and the exported cleaned dataset in Excel format.
        </p>
      </div>

      {error && (
        <Alert variant="danger" onDismiss={() => setError(null)}>
          {error}
        </Alert>
      )}

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* PDF Report Card */}
        <Card className="hover:border-indigo-300 transition-colors">
          <CardHeader>
            <div className="h-10 w-10 rounded-lg bg-indigo-50 dark:bg-indigo-950/30 text-indigo-600 flex items-center justify-center mb-2">
              <FileOutput className="h-5 w-5" />
            </div>
            <CardTitle>Comprehensive Quality Report (.PDF)</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-sm text-gray-600 dark:text-gray-400 leading-relaxed">
              Complete publication-grade documentation containing dataset summary, quality score cards, detailed 14-rule validation logs, and anomaly detection highlights generated by ReportLab.
            </p>
            <div className="pt-2">
              <Button
                onClick={handleDownloadPdf}
                disabled={downloadingPdf}
                className="w-full gap-2"
              >
                <Download className={`h-4 w-4 ${downloadingPdf ? 'animate-bounce' : ''}`} />
                {downloadingPdf ? 'Generating PDF...' : 'Download PDF Report'}
              </Button>
            </div>
          </CardContent>
        </Card>

        {/* Cleaned Dataset Excel Card */}
        <Card className="hover:border-emerald-300 transition-colors">
          <CardHeader>
            <div className="h-10 w-10 rounded-lg bg-emerald-50 dark:bg-emerald-950/30 text-emerald-600 flex items-center justify-center mb-2">
              <FileSpreadsheet className="h-5 w-5" />
            </div>
            <CardTitle>Cleaned Dataset (.XLSX)</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-sm text-gray-600 dark:text-gray-400 leading-relaxed">
              The cleaned, imputed, deduplicated, and formatted output table in Excel (.xlsx) format, ready for downstream analysis or machine learning model training.
            </p>
            <div className="pt-2">
              <Button
                onClick={handleDownloadExcel}
                disabled={downloadingExcel}
                variant="secondary"
                className="w-full gap-2 text-emerald-700 hover:text-emerald-800"
              >
                <Download className={`h-4 w-4 ${downloadingExcel ? 'animate-bounce' : ''}`} />
                {downloadingExcel ? 'Preparing Excel...' : 'Download Cleaned Excel'}
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
